sudo: false

language: python

env:
    global:
        - CC=gcc-4.8
        - CXX=g++-4.8
        - NIX_LIBDIR=$PWD/nix/inst/lib
        - NIX_INCDIR=$PWD/nix/inst/include
        - export PKG_CONFIG_PATH=$NIX_LIBDIR/pkgconfig
        - export PYTHONPATH=$PYTHONPATH:$PWD/neo:$PWD/nixpy

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - kalakris-cmake
      - boost-latest
    packages:
      - libcppunit-dev
      - libboost1.55-all-dev
      - libhdf5-serial-dev
      - cmake
      - g++-4.8

install:
    - pip install numpy quantities
    # nix
    - git clone https://github.com/G-Node/nix.git nix
    - cd nix
    - cmake -DCMAKE_INSTALL_PREFIX=./inst -DBUILD_TESTING=OFF .
    - make
    - make install
    - cd ..
    # nixpy
    - git clone https://github.com/G-Node/nixpy.git nixpy
    - cd nixpy
    - python setup.py build
    - cd ..
    # neo
    - git clone https://github.com/apdavison/python-neo neo
    - cd neo
    - python setup.py build
    - cd ..

script:
    nosetests
