sudo: false

language: python

matrix:
  include:
    - python: "2.7_with_system_site_packages"
      env: COVERALLS=1
    - python: "3.2"
      env: COVERALLS=0

env:
    global:
        - export PYTHONPATH=$PYTHONPATH:$PWD/neo:$PWD/nixpy

addons:
  apt:
    packages:
      - libhdf5-serial-dev

install:
    - pip install numpy quantities coveralls six h5py
    - git clone -b pycore --depth 1 https://github.com/achilleas-k/nixpy.git nixpy
    - git clone -b master --depth 1 https://github.com/NeuralEnsemble/python-neo neo

script:
    - python setup.py build
    - if [ $COVERALLS = 1 ]; then
        coverage run --source=neonix setup.py test && coverage report -m;
      else
        python setup.py test;
      fi;

after_success:
    - if [ $COVERALLS = 1 ]; then
        coveralls;
      fi;
